/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PharmaChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchIds"
      | "batches"
      | "createBatch"
      | "getBatchCount"
      | "owner"
      | "transferBatch"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BatchCreated" | "BatchTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "batches", values: [string]): string;
  encodeFunctionData(
    functionFragment: "createBatch",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferBatch",
    values: [string, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "batchIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "batches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferBatch",
    data: BytesLike
  ): Result;
}

export namespace BatchCreatedEvent {
  export type InputTuple = [id: string, creator: AddressLike];
  export type OutputTuple = [id: string, creator: string];
  export interface OutputObject {
    id: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchTransferredEvent {
  export type InputTuple = [id: string, from: AddressLike, to: AddressLike];
  export type OutputTuple = [id: string, from: string, to: string];
  export interface OutputObject {
    id: string;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PharmaChain extends BaseContract {
  connect(runner?: ContractRunner | null): PharmaChain;
  waitForDeployment(): Promise<this>;

  interface: PharmaChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  batches: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, boolean] & {
        id: string;
        compoundId: string;
        timestamp: bigint;
        currentHolder: string;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  createBatch: TypedContractMethod<
    [_id: string, _compoundId: string],
    [void],
    "nonpayable"
  >;

  getBatchCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  transferBatch: TypedContractMethod<
    [_id: string, _to: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "batches"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, boolean] & {
        id: string;
        compoundId: string;
        timestamp: bigint;
        currentHolder: string;
        isVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createBatch"
  ): TypedContractMethod<
    [_id: string, _compoundId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBatchCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferBatch"
  ): TypedContractMethod<[_id: string, _to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BatchCreated"
  ): TypedContractEvent<
    BatchCreatedEvent.InputTuple,
    BatchCreatedEvent.OutputTuple,
    BatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "BatchTransferred"
  ): TypedContractEvent<
    BatchTransferredEvent.InputTuple,
    BatchTransferredEvent.OutputTuple,
    BatchTransferredEvent.OutputObject
  >;

  filters: {
    "BatchCreated(string,address)": TypedContractEvent<
      BatchCreatedEvent.InputTuple,
      BatchCreatedEvent.OutputTuple,
      BatchCreatedEvent.OutputObject
    >;
    BatchCreated: TypedContractEvent<
      BatchCreatedEvent.InputTuple,
      BatchCreatedEvent.OutputTuple,
      BatchCreatedEvent.OutputObject
    >;

    "BatchTransferred(string,address,address)": TypedContractEvent<
      BatchTransferredEvent.InputTuple,
      BatchTransferredEvent.OutputTuple,
      BatchTransferredEvent.OutputObject
    >;
    BatchTransferred: TypedContractEvent<
      BatchTransferredEvent.InputTuple,
      BatchTransferredEvent.OutputTuple,
      BatchTransferredEvent.OutputObject
    >;
  };
}
